-- seed_restaurants_france.sql — 27 restaurants français (réels et fictifs)
-- À exécuter après add_opening_hours.sql

SET NAMES utf8mb4;

INSERT INTO restaurants (name, address, location, city, price, cuisine, longitude, latitude, phone_number, michelin_url, website_url, award, stars, green_star, facilities, description, opening_hours) VALUES

-- ── 3 ÉTOILES ────────────────────────────────────────────────────────────────

('Guy Savoy',
 'Monnaie de Paris, 11 Quai de Conti, Paris, 75006, France',
 'Paris, France', 'Paris', '€€€€', 'Creative, Classic French',
 2.3388, 48.8572, '+33143804061',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/guy-savoy',
 'https://www.guysavoy.com/',
 '3 Stars', 3, 0,
 'Air conditioning,Interesting wine list,Wheelchair access',
 'Installed in the magnificent halls of the Monnaie de Paris since 2015, Guy Savoy continues to embody culinary excellence with a cuisine that combines classic French technique and bold creativity. The iconic artichoke and black truffle soup remains a must-try, while the sea bass with spiced latte skin demonstrates his mastery of flavours. The service, led by a highly dedicated team, provides an exceptional dining experience in a breathtaking setting overlooking the Seine. The wine list draws on the very greatest French estates, guided by a sommelier of rare erudition.',
 'Mar-Sam · 12h-14h & 19h30-22h | Dim-Lun fermé'),

('Épicure',
 'Hôtel Le Bristol, 112 Rue du Faubourg Saint-Honoré, Paris, 75008, France',
 'Paris, France', 'Paris', '€€€€', 'Classic French, Seasonal Cuisine',
 2.3122, 48.8742, '+33153434300',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/epicure',
 'https://www.oetkercollection.com/hotels/le-bristol-paris/',
 '3 Stars', 3, 0,
 'Air conditioning,Garden or park,Interesting wine list,Wheelchair access',
 'In the sumptuous garden of Le Bristol, Éric Frechon orchestrates a haute cuisine of rare precision and generosity. His macaroni stuffed with black truffle, artichoke and duck foie gras, gratinated with aged Parmesan, has become a Parisian legend. Each course reveals impeccable mastery of classic French techniques, sublimated by exceptional seasonal ingredients. The garden – one of the most beautiful in Paris – transforms the lunch service into a near-magical experience, while the evenings take on the grandeur of a palace-level celebration.',
 'Lun-Dim · 12h-14h & 19h30-22h'),

('Flocons de Sel',
 '1775 Route du Leutaz, Megève, 74120, France',
 'Megève, France', 'Megève', '€€€€', 'Creative, Mountain Cuisine',
 6.6197, 45.8465, '+33450213449',
 'https://guide.michelin.com/fr/auvergne-rhone-alpes/megeve/restaurant/flocons-de-sel',
 'https://www.floconsdesel.com/',
 '3 Stars', 3, 0,
 'Car park,Great view,Interesting wine list,Terrace',
 'Emmanuel Renaut has turned Flocons de Sel into a true temple of alpine gastronomy. His cuisine, deeply rooted in the mountain terroir of Haute-Savoie, revisits ancestral traditions through a contemporary lens of remarkable precision. Crayfish from nearby lakes, wild mushrooms from the surrounding forests and mountain-chalet cheeses inspire creations of touching authenticity. The panoramic terrace overlooking Mont Blanc offers one of the most spectacular dining backdrops in the world, making every table here a genuine privilege.',
 'Mer-Dim · 12h-13h30 & 19h30-21h30 | Lun-Mar fermé'),

('Auberge du Vieux Puits',
 'Route Nationale 613, Fontjoncouse, 11360, France',
 'Fontjoncouse, France', 'Fontjoncouse', '€€€€', 'Creative, Regional Cuisine',
 2.8532, 43.1041, '+33468440737',
 'https://guide.michelin.com/fr/occitanie/fontjoncouse/restaurant/auberge-du-vieux-puits',
 'https://www.aubergeduvieuxpuits.fr/',
 '3 Stars', 3, 0,
 'Car park,Garden or park,Interesting wine list,Terrace',
 'Gilles Goujon has transformed this isolated village of Fontjoncouse in the Corbières into a pilgrimage destination for food lovers worldwide. His cuisine, faithful to the Languedoc terroir, sublimes local products through extraordinary technical mastery. The famous "rotten egg from the earth" dish illustrates his philosophy perfectly: cooking what nature offers with elegance, intelligence and deep respect. The warm, family atmosphere of the auberge adds a unique and disarming dimension to an otherwise stellar gastronomic experience.',
 'Jeu-Lun · 12h-13h30 & 19h30-21h | Mar-Mer fermé'),

('Maison Lameloise',
 '36 Place d''Armes, Chagny, 71150, France',
 'Chagny, France', 'Chagny', '€€€€', 'Classic French, Regional Cuisine',
 4.7518, 46.9068, '+33385871265',
 'https://guide.michelin.com/fr/bourgogne-franche-comte/chagny/restaurant/lameloise',
 'https://www.lameloise.fr/',
 '3 Stars', 3, 0,
 'Air conditioning,Car park,Interesting wine list,Wheelchair access',
 'For three generations, the Lameloise family has made this elegant establishment in the heart of Burgundy a destination of the highest order. Éric Pras perpetuates the tradition of meticulous classical cuisine while bringing his own distinctive creative touches. Iconic Burgundian ingredients – snails, Charolais beef, Bresse chicken – are treated with a reverence that honours centuries of tradition. The exceptional wine cellar, focused on the great growths of the nearby Côte d''Or, adds a final magnificent dimension to an already unforgettable experience.',
 'Mer-Dim · 12h-14h & 19h30-21h30 | Lun-Mar fermé'),

('Auberge de l''Ill',
 '2 Rue de Collonges, Illhaeusern, 68970, France',
 'Illhaeusern, France', 'Illhaeusern', '€€€€', 'Classic French, Alsatian',
 7.5612, 48.1734, '+33389718923',
 'https://guide.michelin.com/fr/grand-est/illhaeusern/restaurant/auberge-de-l-ill',
 'https://www.auberge-de-l-ill.com/',
 '3 Stars', 3, 0,
 'Car park,Garden or park,Interesting wine list,Terrace,Wheelchair access',
 'On the banks of the Ill river, the Haeberlin family has maintained for decades a cuisine of remarkable consistency and elegance. Marc Haeberlin perpetuates and modernises the great classics of Alsatian gastronomy with outstanding precision. The famous salmon soufflé, created by Paul Haeberlin, remains on the menu as a sacred monument to French culinary heritage. The garden, with its willows reflected in the river, creates an enchanting setting where time seems to slow to the gentle rhythm of the seasons.',
 'Mer-Dim · 12h-13h30 & 19h-21h | Lun-Mar fermé'),

-- ── 2 ÉTOILES ────────────────────────────────────────────────────────────────

('Taillevent',
 '15 Rue Lamennais, Paris, 75008, France',
 'Paris, France', 'Paris', '€€€€', 'Classic French',
 2.3053, 48.8734, '+33144951501',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/taillevent',
 'https://www.taillevent.com/',
 '2 Stars', 2, 0,
 'Air conditioning,Interesting wine list,Wheelchair access',
 'The name Taillevent alone evokes the centuries-old history of French gastronomy. In this venerable establishment near the Arc de Triomphe, Giuliano Sperandio perpetuates a classic cuisine of impeccable quality, with great Italian sensitivity woven through each plate. Exceptional products – Breton lobster, Périgord truffles, Landes duck – are treated with a respect that borders on reverence. The legendary wine cellar, one of the finest in Paris, elevates each tasting menu to a deeply memorable experience.',
 'Lun-Ven · 12h-14h & 19h-22h | Sam-Dim fermé'),

('Le Meurice',
 '228 Rue de Rivoli, Paris, 75001, France',
 'Paris, France', 'Paris', '€€€€', 'Creative, Classic French',
 2.3316, 48.8648, '+33144581055',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/le-meurice',
 'https://www.dorchestercollection.com/paris/le-meurice/',
 '2 Stars', 2, 0,
 'Air conditioning,Great view,Interesting wine list,Wheelchair access',
 'Overlooking the Tuileries garden in a room that pays homage to Dalí, Amaury Bouhours deploys a cuisine that is deeply personal and technically impeccable. His signature langoustine with seaweed butter, inspired by a walk on the Breton coast, perfectly illustrates his ability to translate emotional memories into exceptional dishes. Classic French elegance meets unexpected creative verve in every course, earning this palace restaurant its rightful place among Paris''s most cherished gastronomic destinations.',
 'Mar-Sam · 12h-14h & 19h30-22h | Dim-Lun fermé'),

('Kei',
 '5 Rue du Coq-Héron, Paris, 75001, France',
 'Paris, France', 'Paris', '€€€€', 'Creative, Japanese Contemporary',
 2.3453, 48.8626, '+33142336574',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/kei',
 'https://www.restaurant-kei.fr/',
 '2 Stars', 2, 0,
 'Air conditioning,Interesting wine list,Notable sake list',
 'Kei Kobayashi embodies with rare elegance the meeting point between two great culinary civilisations. Trained alongside Alain Ducasse, this Japanese chef of exceptional talent creates a unique cuisine where French techniques and products dialogue harmoniously with the aesthetics and philosophy of Japanese cooking. His peony lobster – at once visually stunning and gustatorily perfect – has become one of the iconic dishes of Parisian gastronomy, a living manifesto of a singular cross-cultural vision.',
 'Mar-Sam · 12h-14h30 & 19h30-22h | Dim-Lun fermé'),

('La Grenouillère',
 '19 Rue de la Grenouillère, Montreuil-sur-Mer, 62170, France',
 'Montreuil-sur-Mer, France', 'Montreuil-sur-Mer', '€€€€', 'Creative, Modern French',
 1.7612, 50.4635, '+33321062907',
 'https://guide.michelin.com/fr/hauts-de-france/montreuil-sur-mer/restaurant/la-grenouillere',
 'https://www.lagrenouillere.fr/',
 '2 Stars', 2, 0,
 'Car park,Garden or park,Interesting wine list,Terrace',
 'Alexandre Gauthier has turned this old farmhouse on the Montreuil marshes into one of the most inventive and personal restaurants in France. His improvisational cuisine, nourished by the surrounding nature and the products of northern France, plays with textures, temperatures and umami flavours with extraordinary virtuosity. There is no fixed menu – instead, an adventure where the chef composes based on the day''s arrivals and his creative impulses. A unique culinary experience that appeals to the most adventurous epicures.',
 'Mer-Dim · 12h-13h30 & 19h30-21h | Lun-Mar fermé'),

('Oustau de Baumanière',
 'Val d''Enfer, Les Baux-de-Provence, 13520, France',
 'Les Baux-de-Provence, France', 'Les Baux-de-Provence', '€€€€', 'Creative, Provençal',
 4.7952, 43.7441, '+33490543307',
 'https://guide.michelin.com/fr/provence-alpes-cote-d-azur/les-baux-de-provence/restaurant/oustau-de-baumaniere',
 'https://www.baumaniere.com/',
 '2 Stars', 2, 0,
 'Air conditioning,Car park,Garden or park,Great view,Interesting wine list,Terrace',
 'Nestled in a spectacular setting among the rocky outcrops of Les Baux-de-Provence, Glenn Viel gives Baumanière''s legendary address a new radiance through a personal, committed cuisine. His deep attachment to the Provençal terroir is expressed through dishes that celebrate local products with audacious creativity: Alpilles lamb, Camargue rice, Rhône valley vegetables. His vegetarian tasting menu, one of the most accomplished in France, demonstrates that plant-based gastronomy can reach summits of true elegance.',
 'Lun-Dim · 12h-14h & 19h30-21h30'),

('Le Pressoir d''Argent',
 '2-5 Place de la Comédie, Bordeaux, 33000, France',
 'Bordeaux, France', 'Bordeaux', '€€€€', 'Creative, Seafood',
 -0.5753, 44.8408, '+33557301010',
 'https://guide.michelin.com/fr/nouvelle-aquitaine/bordeaux/restaurant/le-pressoir-d-argent',
 'https://www.intercontinental-bordeaux.com/',
 '2 Stars', 2, 0,
 'Air conditioning,Interesting wine list,Wheelchair access',
 'In the majestic Grand Hotel de Bordeaux, Frédéric Larquemin deploys a seafood-forward cuisine of great originality. His signature dish – a whole lobster pressed in the famous silver press, creating an intensely flavoured juice that perfects the sauce – is a theatrical and gustatory spectacle that guests never forget. The vast wine list, naturally oriented toward the greatest Bordeaux appellations, allows for extraordinary pairings between exceptional dishes and legendary grand crus.',
 'Mar-Sam · 19h-22h | Dim-Lun fermé'),

-- ── 1 ÉTOILE ─────────────────────────────────────────────────────────────────

('Septime',
 '80 Rue de Charonne, Paris, 75011, France',
 'Paris, France', 'Paris', '€€€', 'Creative, Seasonal Cuisine',
 2.3798, 48.8526, '+33143676829',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/septime',
 'https://www.septime-charonne.fr/',
 '1 Star', 1, 0,
 'Interesting wine list',
 'Bertrand Grébaut has made Septime the emblem of neo-bistro Parisian gastronomy. His radically seasonal cuisine – sourced exclusively from small producers and responsible fishermen – is expressed through dishes of apparent simplicity that conceal extraordinary technical finesse. The menus evolve at the rhythm of the seasons, constituting true snapshots of the moment: a slice of time captured on the plate with poetry and precision. The relaxed, unpretentious atmosphere contrasts agreeably with the sophistication of the cooking.',
 'Lun-Ven · 12h15-14h & 19h15-22h | Sam-Dim fermé'),

('Le Grand Véfour',
 '17 Rue de Beaujolais, Paris, 75001, France',
 'Paris, France', 'Paris', '€€€€', 'Classic French, Creative',
 2.3371, 48.8638, '+33142960627',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/le-grand-vefour',
 'https://www.grand-vefour.com/',
 '1 Star', 1, 0,
 'Air conditioning,Interesting wine list',
 'One of the most beautiful restaurants in the world, the Grand Véfour has been enchanting the Palais-Royal since 1784. Beneath its magnificent painted ceilings and gilded décor listed as a historic monument, the kitchen honours classic French cooking while gently carrying it into the 21st century. Napoleon, Victor Hugo and Colette once sat at these very tables – today''s guests write their own chapter in this living legend of Parisian culinary history.',
 'Lun-Ven · 12h30-14h & 19h30-22h | Sam-Dim fermé'),

('Maison Marcon',
 'Route des Barrages, Saint-Bonnet-le-Froid, 43290, France',
 'Saint-Bonnet-le-Froid, France', 'Saint-Bonnet-le-Froid', '€€€€', 'Creative, Regional Cuisine',
 4.2108, 45.1635, '+33471591293',
 'https://guide.michelin.com/fr/auvergne-rhone-alpes/saint-bonnet-le-froid/restaurant/maison-marcon',
 'https://www.regis-et-jacques-marcon.com/',
 '1 Star', 1, 0,
 'Car park,Great view,Interesting wine list,Terrace',
 'In this remote mountain village of Haute-Loire, Régis and Jacques Marcon have built a true gastronomic sanctuary rooted in the volcanic Auvergne terroir. The wild mushrooms that Régis Marcon has been foraging since childhood inspire an entire corpus of creations of extraordinary depth: ceps, chanterelles and morels become the heroes of dishes where nature expresses itself with unmatched intensity. The panoramic view over the Mézenc massif adds a dimension of wild beauty to this singular culinary pilgrimage.',
 'Mer-Dim · 12h-13h30 & 19h30-21h | Lun-Mar fermé'),

('L''Envol',
 '12 Promenade des Anglais, Nice, 06000, France',
 'Nice, France', 'Nice', '€€€', 'Creative, Mediterranean',
 7.2661, 43.6955, '+33493871234',
 'https://guide.michelin.com/fr/provence-alpes-cote-d-azur/nice/restaurant/l-envol',
 'https://www.lenvol-nice.fr/',
 '1 Star', 1, 0,
 'Air conditioning,Great view,Interesting wine list,Terrace',
 'Perched above the Bay of Angels, L''Envol offers a breathtaking panorama of the Côte d''Azur as the backdrop for a resolutely Mediterranean cuisine. Chef Lucas Moreau celebrates Niçois products with a contemporary spirit: rascasse from the Bay of Angels, socca reimagined as an amuse-bouche, pan bagnat deconstructed into an elegant tasting course. His cooking – deeply local yet open to the world – captures the luminous and generous spirit of the Riviera.',
 'Mar-Sam · 12h30-14h & 19h30-22h | Dim-Lun fermé'),

('La Table de Ventabren',
 '1 Rue Frédéric Mistral, Ventabren, 13122, France',
 'Ventabren, France', 'Ventabren', '€€€', 'Creative, Provençal',
 5.3117, 43.5949, '+33442288079',
 'https://guide.michelin.com/fr/provence-alpes-cote-d-azur/ventabren/restaurant/la-table-de-ventabren',
 'https://www.latabledventabren.com/',
 '1 Star', 1, 0,
 'Car park,Great view,Interesting wine list,Terrace',
 'Perched on a rocky spur overlooking the Arc valley, this charming restaurant offers both a panoramic view and a cuisine intensely anchored in Provence. The chef works exclusively with local producers to create colourful, aromatic dishes that capture the very essence of Provençal sunshine: fresh market-garden vegetables, olive oil from the Château Virant mill, Alpilles lamb, fish from Marseille coastal fishermen. A warm, authentic address that beautifully embodies southern French gastronomy at its finest.',
 'Mar-Sam · 12h-14h & 19h30-21h30 | Dim-Lun fermé'),

('Léon de Lyon',
 '1 Rue Pleney, Lyon, 69001, France',
 'Lyon, France', 'Lyon', '€€€', 'Classic French, Lyonnaise Cuisine',
 4.8326, 45.7676, '+33478289133',
 'https://guide.michelin.com/fr/auvergne-rhone-alpes/lyon/restaurant/leon-de-lyon',
 'https://www.leondelyon.com/',
 '1 Star', 1, 0,
 'Air conditioning,Interesting wine list',
 'Jean-Paul Lacombe perpetuates at Léon de Lyon the noble Lyonnaise culinary tradition with exemplary constancy. Lyon, self-proclaimed capital of French gastronomy, finds here one of its finest ambassadors: pike quenelles, gratinéed onion soup, duck foie gras en croûte de brioche – these great classics are prepared with a respect and precision that honours centuries of tradition. The cellar, a formidable selection of Burgundies, Côtes-du-Rhône and Beaujolais, perfectly completes this hymn to the Lyon terroir.',
 'Mar-Sam · 12h-14h & 19h30-22h | Dim-Lun fermé'),

('Le Quinzième',
 '14 Rue Cauchy, Paris, 75015, France',
 'Paris, France', 'Paris', '€€€', 'Creative French',
 2.2918, 48.8432, '+33145548343',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/le-quinzieme-cyril-lignac',
 'https://www.restaurantlequinzieme.com/',
 '1 Star', 1, 0,
 'Air conditioning,Interesting wine list',
 'Cyril Lignac has made his Quinzième one of the finest creative tables in western Paris. Far from his television image, a meticulous and passionate chef deploys here a personal cuisine of great beauty and precision. Seasonal menus, updated each morning according to the morning market, alternate between classic references and more adventurous explorations. The warm atmosphere and impeccable service make every dinner an authentic and generous shared experience.',
 'Mar-Sam · 12h-14h & 19h-22h | Dim-Lun fermé'),

('La Scène',
 '32 Avenue Matignon, Paris, 75008, France',
 'Paris, France', 'Paris', '€€€€', 'Creative, Modern French',
 2.3161, 48.8743, '+33142655035',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/la-scene',
 'https://www.lascene.com/',
 '1 Star', 1, 0,
 'Air conditioning,Interesting wine list,Wheelchair access',
 'Stéphanie Le Quellec''s La Scène is one of the most elegant dining rooms in the 8th arrondissement. Her cuisine, intensely feminine and deeply personal, draws on her Mediterranean and Lyonnaise roots to create dishes of rare poetry and balance. The signature roasted langoustine with fermented cream and wild herbs is a masterclass in restraint and precision. Her impeccable attention to every detail – from the ceramics to the bread trolley – makes La Scène a complete gastronomic experience of the highest order.',
 'Lun-Ven · 12h-14h & 19h-22h | Sam-Dim fermé'),

-- ── BIB GOURMAND ─────────────────────────────────────────────────────────────

('Bistrot Paul Bert',
 '18 Rue Paul Bert, Paris, 75011, France',
 'Paris, France', 'Paris', '€€', 'Classic French, Bistro',
 2.3817, 48.8518, '+33143729801',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/le-bistrot-paul-bert',
 '',
 'Bib Gourmand', 0, 0,
 'Interesting wine list,Terrace',
 'Bertrand Auboyneau has made the Paul Bert bistro one of the most beloved addresses of authentic Parisian culinary tradition. Here, everything speaks of genuine bistro life: the tiled floor, the zinc counter, the chalk-written slate menus. The cuisine is frank, direct, seasonal and perfectly executed: beef tartare hand-cut to order, roasted bone marrow with fleur de sel, profiteroles with hot chocolate sauce. A living hymn to Parisian bistro culture – unchanged for decades and resolutely faithful to a popular culinary tradition of rare integrity.',
 'Mar-Sam · 12h-14h30 & 19h30-23h | Dim-Lun fermé'),

('Le Comptoir du Relais',
 '9 Carrefour de l''Odéon, Paris, 75006, France',
 'Paris, France', 'Paris', '€€', 'French Bistro, Lyonnaise Cuisine',
 2.3396, 48.8517, '+33144270797',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/le-comptoir-du-relais',
 '',
 'Bib Gourmand', 0, 0,
 'Terrace',
 'Yves Camdeborde, the pioneer of the neo-bistro movement, brings the best of accessible Parisian gastronomy to the Comptoir. His cuisine, direct and seasonal, reveals an exceptional command of product quality and classic French technique. The Saturday evening five-course dinner menu has become a Parisian institution, with reservations required months in advance. The brasserie formula at lunch allows a spontaneous stop for charcuterie, a tartare or a croque-monsieur prepared with the same care. A true address that has marked an entire generation of chefs.',
 'Lun-Dim · 12h-23h'),

('L''Atelier du Peintre',
 '1 Rue Schongauer, Colmar, 68000, France',
 'Colmar, France', 'Colmar', '€€', 'Creative, Alsatian',
 7.3568, 48.0793, '+33389291557',
 'https://guide.michelin.com/fr/grand-est/colmar/restaurant/l-atelier-du-peintre',
 'https://www.atelier-peintre.fr/',
 'Bib Gourmand', 0, 0,
 'Air conditioning,Terrace',
 'In picturesque Little Venice in Colmar, Loïc Lefebvre offers a creative and accessible re-reading of Alsatian cuisine. Far from folksy clichés, his cooking revisits sauerkraut, baeckeoffe and kugelhopf through a fresh, contemporary prism. The short seasonal menu changes daily according to market visits and the chef''s inspirations. An excellent selection of Alsatian wines at fair prices completes this warm, charming address that has become one of the most beloved in the Haut-Rhin.',
 'Mar-Sam · 12h-13h45 & 19h-21h45 | Dim-Lun fermé'),

('Café Moderne',
 '19 Rue Kléber, Rennes, 35000, France',
 'Rennes, France', 'Rennes', '€€', 'Creative, Seasonal Cuisine',
 -1.6778, 48.1147, '+33299798382',
 'https://guide.michelin.com/fr/bretagne/rennes/restaurant/cafe-moderne',
 'https://www.cafemoderne-rennes.fr/',
 'Bib Gourmand', 0, 0,
 'Interesting wine list,Terrace',
 'In the heart of old Rennes, this discreet address has become a favourite of gourmet locals in search of honest cooking and fair prices. The young chef, trained in Parisian kitchens, chose to return to his native Brittany to cook what he loves most: seasonal Breton products handled with care and creativity. Galette de blé noir revisited as a stylish starter, lobster bisque with cider, Breton butter cake with caramel – a resolutely local and proudly regional cuisine served in an effortlessly convivial atmosphere.',
 'Lun-Sam · 12h-14h & 19h-22h | Dim fermé'),

('La Régalade Conservatoire',
 '9 Rue du Conservatoire, Paris, 75009, France',
 'Paris, France', 'Paris', '€€', 'French Bistro, Classic',
 2.3481, 48.8726, '+33344715279',
 'https://guide.michelin.com/fr/ile-de-france/paris/restaurant/la-regalade-conservatoire',
 '',
 'Bib Gourmand', 0, 0,
 'Interesting wine list',
 'Bruno Doucet''s concept has found a new home near the Grands Boulevards with this busy, cheerful address. The menu offers the very best of French bistro cooking: generous, flavourful and without pretension, yet always perfectly executed. The country terrine served in its entire jar, sweetbreads with morel mushrooms, profiteroles with hot chocolate – regulars return week after week for these indispensable dishes. Convivial atmosphere, reasonable prices and a quality that never wavers: the perfect Parisian bistronomy.',
 'Lun-Ven · 12h-14h30 & 19h-22h30 | Sam-Dim fermé'),

-- ── GREEN STAR ────────────────────────────────────────────────────────────────

('La Marine',
 '1 Rue Marie Lemonnier, Noirmoutier-en-l''Île, 85330, France',
 'Noirmoutier-en-l''Île, France', 'Noirmoutier-en-l''Île', '€€€€', 'Creative, Seafood',
 -2.2569, 46.9832, '+33251390009',
 'https://guide.michelin.com/fr/pays-de-la-loire/noirmoutier-en-l-ile/restaurant/la-marine',
 'https://www.alexandrecouillon.com/',
 'Green Star', 0, 1,
 'Air conditioning,Interesting wine list,Terrace,Wheelchair access',
 'Alexandre Couillon has made La Marine a world reference in committed oceanic gastronomy. His deeply ecological approach – local fishing, kitchen garden on the island, zero waste – is combined with extraordinary culinary talent to produce dishes of rare intensity and honesty. Every morning he meets the fishermen, every day he visits his gardens: this daily ritual nourishes a resolutely seasonal and living cuisine. His sea purslane soup, dried fish on salt marsh hay and spider crab in seaweed bouillon have become emblematic dishes of a sincere, committed gastronomy.',
 'Mar-Sam · 12h-13h30 & 19h30-21h30 | Dim-Lun fermé'),

('Le Jardin des Plumes',
 '1 Rue du Milieu, Giverny, 27620, France',
 'Giverny, France', 'Giverny', '€€€', 'Creative, Seasonal Cuisine',
 1.5358, 49.0772, '+33232540026',
 'https://guide.michelin.com/fr/normandie/giverny/restaurant/le-jardin-des-plumes',
 'https://www.jardindesplumes.fr/',
 'Green Star', 0, 1,
 'Car park,Garden or park,Interesting wine list,Terrace',
 'In the village of Monet, David Gallienne has created a culinary address as poetic as its surroundings. His cuisine, one of the most ecologically committed in Normandy, transforms the local terroir into impressionist paintings on the plate. Every vegetable comes from the kitchen garden planted in the spirit of Monet''s famous garden, every apple from neighbouring orchards, every fish from the nearby Norman coast. The seasonal, vegetable-forward tasting menu changes weekly, offering extraordinary finesse and narrative depth in every course.',
 'Jeu-Lun · 12h-14h & 19h30-21h30 | Mar-Mer fermé');
