-- seed.sql — Données initiales restaurants Guide Michelin

SET NAMES utf8mb4;

INSERT INTO restaurants (name, address, location, city, price, cuisine, longitude, latitude, phone_number, michelin_url, website_url, award, stars, green_star, facilities, description) VALUES
('ES:SENZ', 'Mietenkamer Straße 65, Grassau, 83224, Germany', 'Grassau, Germany', 'Grassau', '€€€€', 'Creative, Modern Cuisine', 12.4656176, 47.7856302, '+498641401609', 'https://guide.michelin.com/en/bayern/grassau/restaurant/es-senz', 'https://www.das-achental.com/essenz', '3 Stars', 3, 0, 'Air conditioning,Car park,Interesting wine list', 'From the get-go, the stage is set in grand style: Following a spectacular overture in the form of various aperitifs, an artisanal bread selection and amuse-bouches, Edip Sigl reveals why it is worth making the trip to dine at this restaurant in Das Achental hotel. He presents two incredible set menus: "Chiemgau pur" (devoted to the region) and "Chiemgau goes around the world" (a combination of local and international ingredients). Both feature modern creations that are complex but not overdone, highly refined and consistently elegant – think langoustine, artichoke, kumquat, pea, bisque, or the Sigl classic of saffron ice cream with fermented rosehip and pumpkin seed oil. In dishes such as the Miéral squab on the bone, the chef also proves he can deliver robust flavours. Diners are free to opt for six or eight courses, with the added bonus that sauces are left at the table to allow for second helpings. Expert service adds the finishing touch: approachable and courteous, pleasingly laid back and full of Bavarian charm, making the guest the true focus. Tip: Nab a table by the floor-to-ceiling windows of the elegant dining space and enjoy the view of the garden.'),

('Tohru in der Schreiberei', 'Burgstraße 5, Munich, 80331, Germany', 'Munich, Germany', 'Munich', '€€€€', 'Modern Cuisine, Japanese Contemporary', 11.577475, 48.137597, '+498921529172', 'https://guide.michelin.com/en/bayern/mnchen/restaurant/tohru-in-der-schreiberei', 'https://schreiberei-muc.de/', '3 Stars', 3, 0, 'Interesting wine list,Notable sake list', 'It is absolutely worth climbing the 23 steps of the beautiful steep wooden staircase that leads to this tasteful, upscale restaurant, which has been designed with an eye for detail. In this historic location (Munich''s oldest town house, where the city''s history started to be recorded in 1552), Tohru Nakamura – a Munich-born chef of German-Japanese descent – artfully bridges the gap between classic French and European cuisine and the culinary traditions of Japan. The combination of ingredients and flavours from both cultures makes for a unique twist, for example, in the perfectly cooked, delicately aromatic Koshihikari rice with excellent regional trout caviar and a hint of wasabi, as well as an intense beurre blanc made from fermented rice, sake and elderflower. A tasting menu comprising 10 or eight courses is proposed. The attentive waitstaff are always on hand to elucidate the chef''s culinary concept. When it comes to wine recommendations (tip: Rieslings), you are in the best hands with sommelier Christian Rainer. A nice touch: Diners are even greeted with a tour of the kitchen!'),

('Schwarzwaldstube', 'Tonbachstraße 237, Baiersbronn, 72270, Germany', 'Baiersbronn, Germany', 'Baiersbronn', '€€€€', 'Classic French, Creative', 8.3582803, 48.5369113, '+497442492665', 'https://guide.michelin.com/en/baden-wurttemberg/baiersbronn/restaurant/schwarzwaldstube', 'https://www.traube-tonbach.de/kulinarik/schwarzwaldstube/', '3 Stars', 3, 0, 'Air conditioning,Car park,Great view,Interesting wine list,Wheelchair access', 'Schwarzwaldstube, the flagship restaurant of the Traube Tonbach hotel, is modern and elegant with a regional flavour; the floor-to-gable glass-paned façade affords unobstructed views of the valley. Chef Torsten Michel and his team bowl diners over with a savvy mix of dishes that draw on modern and classic influences. Made using top-notch ingredients, his clearly structured creations are brimming with finesse and flavours. Diners are offered a choice between a shorter and a longer tasting menu, as well as a vegetarian set menu. A tempting standout dish is the Norwegian langoustine, with an intensely flavoursome roe glaze, on a bed of aromatic peas and black morels, and accompanied by a Chablis nage with zesty lemon notes. Piet Gliesche''s wonderful desserts are the perfect ending to any meal. As an alternative to the set menu, there is a fantastic à la carte selection including, for example, sea bass for two. And then there is the extremely pleasant, perfectly organised service team supporting Stéphane Gass, a highly competent maître d'' and sommelier with bags of personality.'),

('Victor''s Fine Dining by christian bau', 'Schlossstraße 27, Perl, 66706, Germany', 'Perl, Germany', 'Perl', '€€€€', 'Creative, Contemporary', 6.3872109, 49.5351732, '+49686679118', 'https://guide.michelin.com/en/saarland/perl/restaurant/victor-s-fine-dining-by-christian-bau', 'https://www.victors-fine-dining.de/', '3 Stars', 3, 0, 'Air conditioning,Car park,Interesting wine list,Notable sake list', 'The way in which Christian Bau combines influences from French and Japanese cuisine makes for truly memorable results! His unique signature style runs through the entire menu. The "Paris – Tokyo" set menu allows you to experience the best possible ingredient quality and witness his impressive aplomb. It is with consummate craftsmanship that he pairs, for example, the freshest tuna fillet in the form of tartare and raw slices with Imperial caviar, marinated daikon radish and an umami-rich seaweed and ginger vinaigrette, and creates delicate contrasts by adding crispy seaweed chips, fresh cress and shiso leaves. His highly aromatic signature dish "bau.stein – Pan Dan, exotic fruits, coconut yuzu ice cream" also meets the most exacting of standards. He skilfully implements new ideas while remaining true to his style. There is also a range of specials with which to supplement the set menu. The wine list is extensive, with a particularly good selection of regional wines from the Moselle and Saar. The professional and friendly service adds to the experience. In addition there is the option of staying overnight at the elegant Victor''s Residenz-Hotel Schloss Berg.'),

('schanz. restaurant.', 'Bahnhofstraße 8a, Piesport, 54498, Germany', 'Piesport, Germany', 'Piesport', '€€€€', 'Modern French, Creative', 6.9266002, 49.8776003, '+49650792520', 'https://guide.michelin.com/en/rheinland-pfalz/piesport/restaurant/schanz-restaurant', 'https://www.schanz-restaurant.de/de/', '3 Stars', 3, 0, 'Air conditioning,Car park,Wheelchair access', 'It is thanks to Thomas Schanz that this small town on the Mosel, already known for its excellent wines, has also become a mecca for foodies. With his own distinctive style, he puts a modern spin on classic cuisine. The dishes are very precisely and delicately crafted using ingredients of outstanding quality. Prepared with a very personal touch, one of the chef-patron''s signature classics is his pot-au-feu, which is adapted to each season – at the time of our visit it featured rabbit saddle, kidney and liver, young root vegetables and lovage – simply wonderful! Good to know: Alongside the set menu, there is also a fine à la carte selection. The wine list includes fantastic labels from the Mosel, complemented by selections from France and Italy, and the cordial sommelier, Janine Löwenberg, provides astute recommendations. The elegant interior, with its warm tones and local materials, references the region. Floor-to-ceiling windows look out onto the courtyard. Thomas Schanz is not only a trained chef but also a hotelier, and there are tasteful guestrooms in the hotel he has taken over from his parents.'),

('Restaurant Haerlin', 'Neuer Jungfernstieg 9, Hamburg, 20354, Germany', 'Hamburg, Germany', 'Hamburg', '€€€€', 'Creative French, Classic Cuisine', 9.9914638, 53.5554424, '+494034940', 'https://guide.michelin.com/en/hamburg-region/hamburg/restaurant/haerlin', 'https://restaurant-haerlin.de/de/', '3 Stars', 3, 0, 'Air conditioning,Great view,Interesting wine list,Wheelchair access', 'One of Hamburg''s classic hotels, the legendary Hotel Vier Jahreszeiten, with its view of the Inner Alster Lake, is home to this stylish, chic restaurant. The top-notch cuisine is inextricably linked with Christoph Rüffer, who has been the chef here for over 20 years. His dishes adhere to a clear idea, retaining their identity despite considerable technicality. He incorporates meaningful contrasts with minimal fuss. Each elegant course of the perfectly composed menu is beautifully balanced. There are also several dishes to swap out or add on. The mainstay of the cuisine is top-notch ingredients – the langoustine and the saddle of venison are particularly noteworthy, not to mention the fantastic sauces! Proficient service is provided by a classic-style brigade. The wine list is outstanding; the wine pairings devised for the set menu can be highly recommended. For a little luxury… world-class wines are also available by the glass.'),

('The Table Kevin Fehling', 'Shanghaiallee 15, Hamburg, 20457, Germany', 'Hamburg, Germany', 'Hamburg', '€€€€', 'Creative, International', 10.0030728, 53.5424857, '+494022867422', 'https://guide.michelin.com/en/hamburg-region/hamburg/restaurant/the-table-kevin-fehling', 'https://thetable-hamburg.de/', '3 Stars', 3, 0, 'Air conditioning,Counter dining', 'In his set menu (dubbed "Das Tor zur Welt" – "Gateway to the World"), Kevin Fehling makes use of a wide variety of ingredients – Asian, Middle Eastern and South American – and also likes to combine these, crossover style, with classic French-based cuisine. An array of wonderfully complementary flavours turn creations such as "The Sea – poached oyster, hamachi, sea urchin & horseradish" or "Ballotine of quail, aubergine, kumquat, argan oil cream & saffron broth" into characteristic dishes that shine in terms of the quality of the produce, precision, and depth of flavour. In the stylish, relaxed atmosphere at the long and winding table after which the restaurant is named, you can see the action unfold in the kitchen – everything runs like a well-oiled machine or an orchestra! Restaurant manager David Eitel, part of the charming, attentive service team, who interact with guests in a laid-back manner, should also be mentioned.'),

('Waldhotel Sonnora', 'Auf''m Eichelfeld 1, Dreis, 54518, Germany', 'Dreis, Germany', 'Dreis', '€€€€', 'Classic French', 6.8109342, 49.9377323, '+49657898220', 'https://guide.michelin.com/en/rheinland-pfalz/dreis/restaurant/waldhotel-sonnora', 'https://www.hotel-sonnora.de/', '3 Stars', 3, 0, 'Car park,Garden or park,Interesting wine list', 'This legendary fine dining establishment has an exemplary pair of hosts in husband-and-wife team Magdalena and Clemens Rambichler. In the kitchen, the chef cultivates the house specialities, such as "Kleine Torte" of beef tenderloin tartare with N25 caviar, but also showcases his own style. Top-notch ingredients are precisely prepared, down to the last detail, without the importance of flavour ever being lost from sight. This starts with the amuse-bouches (a veritable explosion of flavours!), followed, for example, by the excellent firm-fleshed, charcoal-grilled turbot from the Vendeé – which has a wonderful smoky aroma – harmoniously combined with terrific fresh black morels, fine white asparagus and a very elegant PX sherry note in the classic beurre noisette. The set menu features two intriguing wine pairings. You can also dine à la carte. Magdalena Rambichler is always on hand, cordial and extremely competent as she heads up the service team. The decor is stylish, elegant and discreetly modern. The inviting individually designed guestrooms are equally fabulous.'),

('JAN', 'Luisenstraße 27, Munich, 80333, Germany', 'Munich, Germany', 'Munich', '€€€€', 'Creative, Modern Cuisine', 11.5629878, 48.1447975, '+498923708658', 'https://guide.michelin.com/en/bayern/mnchen/restaurant/jan-1204321', 'https://jan-hartwig.com/', '3 Stars', 3, 0, 'Interesting wine list', 'This restaurant has firmly established itself among the world''s top-tier dining destinations. The ability of Jan Hartwig and his team to bridge the gap between French culinary artistry and German classics is impressive. Dishes such as meatloaf, egg with mustard sauce and Handkas mit Musik are transformed into something spectacular. Each creation dazzles – the quality of the ingredients is beyond question, and the craftsmanship is masterful. In the seven-course set menu, every detail is precisely executed and well thought out, with a clear sense of identity, featuring inventive and sometimes surprising combinations. You have the option to add various signature dishes such as "sea urchin ''Louise''" or pâté en croûte. The set menu is available at lunch and dinnertime – it''s also possible to have a shortened version at lunchtime. Depending on where you sit in the sleek, chic and upscale interior, you can look through the open door or open pass into the kitchen, dubbed the Labor der Liebe ("Laboratory of Love"). The atmosphere is harmonious, and the service team led by maître d'' Kilian Skalet is dedicated and professional. The impressive wine list includes specialities such as magnums, jeroboams and special vintages.'),

('Restaurant Bareiss', 'Hermine-Bareiss-Weg 1, Baiersbronn, 72270, Germany', 'Baiersbronn, Germany', 'Baiersbronn', '€€€€', 'Classic French, Seasonal Cuisine', 8.3268245, 48.5201324, '+497442470', 'https://guide.michelin.com/en/baden-wurttemberg/baiersbronn/restaurant/restaurant-bareiss', 'https://www.bareiss.com/', '3 Stars', 3, 0, 'Air conditioning,Car park,Interesting wine list,Wheelchair access', 'Claus-Peter Lumpp has been head chef at the fine dining restaurant of the luxurious Hotel Bareiss since March 1992, and his cooking is renowned far beyond the confines of the Black Forest. His style is rooted in classic French culinary tradition but also incorporates international influences. The amuse-bouches are fantastic – warm dumplings with a flavourful lobster filling and an aromatic broth made from watermelon, lemon balm and a hint of chilli. The extensive and elaborate dessert creations by head pastry chef Stefan Leitner also deserve a mention – be sure to leave some room for the pralines from the trolley! The decor is upscale further to a modern makeover incorporating elegant details such as hand-cut alabaster designer lamps, chic upholstered chairs and a palette of warm tones. However, the original character of the building has been retained. And then there is the highly professional service team headed up by maître d'' Thomas Brandt, plus excellent wine recommendations courtesy of sommelier Teoman Mezda. It''s a bonus that you can also partake in this culinary experience at lunchtime.'),

('Rutz', 'Chausseestraße 8, Berlin, 10115, Germany', 'Berlin, Germany', 'Berlin', '€€€€', 'Modern Cuisine, Creative', 13.3860867, 52.5283507, '+493024628760', 'https://guide.michelin.com/en/berlin-region/berlin/restaurant/rutz', 'https://rutz-restaurant.de/', '3 Stars', 3, 1, 'Air conditioning,Interesting wine list,Terrace', 'Marco Müller''s "Inspiration" tasting menu unfolds as a culinary journey, shaped by a clear personal style and a skilfully constructed narrative arc. The service team explains the ideas behind the dishes in a pleasingly relaxed and informal manner, and is always happy to answer questions. The kitchen works with remarkable precision, yet the cooking retains a sense of effortlessness and balance. With only a few components, the dishes seem minimalist, but are packed with details that lend them exceptional depth. One standout dish is the tender, flawlessly cooked Oldenburg Wagyu with an umami-rich beef garum, crisp kohlrabi strips and a hollandaise brimming with intensity. Even adventurous pairings, like North Sea squid with red cabbage, work remarkably well. Ingredients are sourced from carefully selected suppliers known personally to the chef, all of exceptional quality. The set menu comprises 12 or 13 "inspirations", with an optional caviar course available. The terrace, small but welcoming, is the ideal spot in summer.'),

('Maaemo', 'Dronning Eufemias gate 23, Oslo, 0194, Norway', 'Oslo, Norway', 'Oslo', '€€€€', 'Creative', 10.7586363, 59.9075293, '+4722179969', 'https://guide.michelin.com/en/oslo-region/oslo/restaurant/maaemo-1194933', 'https://www.maaemo.no', '3 Stars', 3, 1, 'Air conditioning,Interesting wine list', 'Time seems to stand still when you dine at this truly exceptional restaurant, such is its overwhelming quality. The unique dining experience begins with a drink in the cosy lounge before moving into a dramatic, high-ceilinged dining room with a theatrically lit open kitchen. A surprise seasonal tasting menu comprises a succession of expertly crafted, consistently memorable dishes that deliver sublime flavours and textures in superbly conceived combinations.'),

('RE-NAA', 'Nordbøgata 8, Stavanger, 4006, Norway', 'Stavanger, Norway', 'Stavanger', '€€€€', 'Creative, Seafood', 5.7308447, 58.9739705, '+4751551111', 'https://guide.michelin.com/en/rogaland/stavanger/restaurant/re-naa', 'https://www.restaurantrenaa.no/', '3 Stars', 3, 0, 'Air conditioning,Interesting wine list,Wheelchair access', 'The kitchen quite literally takes centre stage at this impeccable restaurant, sitting in the middle of the stylish room and providing a stage for the chefs to prepare intricate, superbly crafted dishes. Top-notch local fish and shellfish underpins the cooking, with supreme skill evident in the refined balance between the delicate seafood flavours and some stronger components – the grilled scallop with sea buckthorn and pumpkin sauce is a perfect example. The menu has around 20 servings and every aspect unfolds masterfully thanks to the exceptional kitchen and service teams.'),

('Frantzén', 'Klara Norra Kyrkogata 26, Stockholm, 111 22, Sweden', 'Stockholm, Sweden', 'Stockholm', '€€€€', 'Creative', 18.0597575, 59.3341673, '+468208580', 'https://guide.michelin.com/en/stockholm-region/stockholm/restaurant/frantzen', 'https://www.restaurantfrantzen.com/', '3 Stars', 3, 0, 'Air conditioning,Counter dining,Interesting wine list', 'World-renowned Chef Björn Frantzén provides a truly immersive experience that you won''t forget in a hurry at his uber-stylish restaurant. Ring the bell to enter, before enjoying an aperitif in the top-floor lounge while the day''s ingredients are explained, then head to the dining room with its beautiful counter seating to witness the exceptionally talented chefs at work as they craft creative, perfectly executed dishes. The service works like clockwork to enhance the experience.'),

('Jordnær', 'Gentoftegade 29, Gentofte, 2820, Denmark', 'Gentofte, Denmark', 'Gentofte', '€€€€', 'Creative', 12.5412347, 55.7481416, '+4522408020', 'https://guide.michelin.com/en/capital-region/gentofte_1373269/restaurant/jordnaer', 'https://www.restaurantjordnaer.dk/', '3 Stars', 3, 0, 'Car park,Interesting wine list', 'Chef-Owner Eric Kragh Vildgaard is the driving force behind this remarkable dining experience, demonstrating enormous technical skill across his procession of bold and creative dishes, all founded on seafood and vegetable produce of the utmost quality. The cooking varies between the wisely restrained (the pure, precise hamachi, ponzu and wasabi) and the hyper-detailed (the stunningly plated, multi-layered chawanmushi). Tina oversees the charming service in this stylish and sophisticated oasis, which is expertly run at every turn.'),

('Geranium', 'Per Henrik Lings Allé 4, Parken National Stadium, Copenhagen, 2100 Ø, Denmark', 'Copenhagen, Denmark', 'Copenhagen', '€€€€', 'Creative, Contemporary', 12.5720951, 55.703472, '+4569960020', 'https://guide.michelin.com/en/capital-region/copenhagen/restaurant/geranium', 'https://www.geranium.dk/', '3 Stars', 3, 0, 'Air conditioning,Great view,Interesting wine list,Wheelchair access', 'The 8th floor of the Parken Stadium – home to F.C. Copenhagen and the Danish national team – is the unlikely setting for Rasmus Kofoed''s luxurious, world-class restaurant that''s in a league of its own. Panoramic park views are accompanied by around 15 meticulously prepared, beautifully presented courses, with each one as highly creative and impeccably precise as the last. Totally eschewing meat, the first-rate ingredients include biodynamic vegetables, foraged plants and berries, and seafood from non-endangered species. A stunningly stocked wine cellar rounds out the experience.'),

('Hiša Franko', 'Staro selo 1, Kobarid, 5222, Slovenia', 'Kobarid, Slovenia', 'Kobarid', '€€€€', 'Creative, Regional Cuisine', 13.5378132, 46.247312, '+38653894120', 'https://guide.michelin.com/en/gorizia/kobarid/restaurant/hisa-franko', 'https://www.hisafranko.com/', '3 Stars', 3, 1, 'Air conditioning,Car park,Interesting wine list,Wheelchair access', 'Few kitchens reflect their chef''s personality as clearly as Chef Ana Roš Stojan''s. Her strong, determined character and infectious warmth find perfect expression in a single tasting menu where dishes possess bold, decisive flavors with no compromise. Each course is a discovery: local ingredients and Slovenian traditions converse with international influences, balanced through refinement, taste, and technical precision. The Orme menu traces this journey with distinctly characterized yet elegant dishes, animated by a note of vivacious and refined freshness. Dishes that captivate on sight through a meticulous, colorful presentation, while surprising at every bite. Among the most compelling offerings are the Cappelletti, "Saporito delle valli" with tonka and fig leaves: the creaminess of the sauce and balanced flavors create a singular experience. Among the house specialties, which are nearly always on the menu, don''t miss the corn beignet with fermented ricotta cheese and smoked trout roe, and the hay-baked potatoes with fenugreek and roasted yeast-infused sour cream – dishes that authentically express the chef''s identity. Completing the experience, the service is impeccable, orchestrated by a young, cohesive team who guide guests with professionalism, ease, and passion, eloquently describing dishes and suggesting targeted wine pairings. For overnight guests, breakfast is unmissable: generous, colorful, and meticulously composed.'),

('Trèsind Studio', 'St. Regis Gardens, The Palm Jumeirah, Dubai', 'Dubai', 'Dubai', '$$$$', 'Indian', 55.1391176, 25.114932, '+971588951272', 'https://guide.michelin.com/en/dubai-emirate/dubai/restaurant/tresind-studio', 'https://tresindstudio.com/', '3 Stars', 3, 0, 'Air conditioning,Valet parking', 'The surprise multi-course tasting menu is a masterpiece of originality, intrigue and precision, featuring flavours and tastes from all four compass points of India. While the chefs work away with quiet diligence and focus in the open kitchen, the service team provide detailed explanations of each elegant creation. A little theatre here and there with certain courses adds to an unforgettable experience. There''s something magical happening here – and with just 15 seats and a rooftop location – you''ll feel you''re in on the secret. Pro tip: arrive to dinner a little earlier to enjoy signature cocktails at the Popadom Botanic Bar.'),

('Grande Étoile', 'Bastionstraße 16, Düsseldorf, 40213, Germany', 'Düsseldorf, Germany', 'Düsseldorf', '€€€', 'Modern Cuisine, French', 6.775079, 51.221634, '+4921115884815', 'https://guide.michelin.com/en/nordrhein-westfalen/dusseldorf/restaurant/grande-etoile', 'https://www.grande-etoile.com/', 'Selected Restaurants', 0, 0, 'Air conditioning,Terrace', 'This restaurant in the Carlstadt district is a masterclass in chic: shimmering gold, velvet, striking chandeliers and stylish Art Deco features create a trendy, elegant atmosphere. It serves up flavourful, well-executed dishes from a menu featuring French brasserie classics as well as Italian influences: beef bourguignon, beef tartare, pasta, vitello al limone... Service is professional and friendly. Head there in the evening for the cocktail bar and DJs, who underscore the Parisian club vibe.'),

('Goldener Engel', 'Bachenstraße 27, Ihringen, 79241, Germany', 'Ihringen, Germany', 'Ihringen', '€€', 'Regional Cuisine', 7.6472096, 48.0439756, '+497668908870', 'https://guide.michelin.com/en/baden-wurttemberg/ihringen/restaurant/goldener-engel', 'https://engel-ihringen.de/', 'Selected Restaurants', 0, 0, 'Car park,Credit cards not accepted,Terrace', 'Steeped in tradition and brimming with regional charm, this establishment is staffed by a young and adept team who deliver pleasingly down-to-earth yet ambitious cuisine. While the friendly proprietress Emma Ambs, who hails from a family of restaurateurs in the next village, attentively manages the service, Simon Bantle (a veteran of various MICHELIN-starred kitchens) fuses hearty traditional fare with classic French recipes. The dishes are meticulously prepared, packed with flavour and delightfully unpretentious – think jellied veal tripe with fried potatoes, or braised ox cheeks with Ihringen pinot noir jus, served with creamed kohlrabi, kohlrabi purée and pommes dauphine. Featuring labels from the region, as well as elsewhere in Germany and beyond, the well-curated wine list is worth exploring. Modern guestrooms are available in the adjoining hotel of the same name.'),

('Chiemgauhof', 'Julius-Exter-Promenade 21, Übersee, 83236, Germany', 'Übersee, Germany', 'Übersee', '€€€', 'Farm to table, Regional Cuisine', 12.4757464, 47.8468221, '+4986423179800', 'https://guide.michelin.com/en/bayern/ubersee_1280400/restaurant/chiemgauhof', 'https://www.chiemgauhof.com/de/chiemgauhof-restaurant.html', 'Selected Restaurants', 0, 0, 'Air conditioning,Car park,Great view,Terrace,Wheelchair access', 'The restaurant of the exclusive Chiemgau Lakeside Retreat, an offshoot of the nearby Resort Das Achental in Grassau, draws you in with its enticing lakeside location – right by Chiemsee. In fine weather, the lake view is best from the terrace, but, thanks to the floor-to-ceiling windows, you won''t be deprived even if you dine inside. The decor in the dining rooms, which can be separated off by means of a glass partition, is an attractive blend of traditional regional elements such as warm wood and a stylish classic tiled stove and modern sleek lines. This combination is also reflected in the cuisine, which sees regional influences given a modern makeover.'),

('Chefs Atelier', 'Im Löwental 60A, Essen, 45239, Germany', 'Essen, Germany', 'Essen', '€€€€', 'Creative, Seasonal Cuisine', 6.9957349, 51.3836464, '+4920164613366', 'https://guide.michelin.com/en/nordrhein-westfalen/essen/restaurant/chefs-atelier', 'https://www.chefsatelier.de', '1 Star', 1, 0, 'Car park', 'A staircase leads down to this restaurant sporting a modern look. The first appetisers are served in the lounge as an aperitif, before a maximum of 18 guests are seated at their tables in a relaxed atmosphere. The open kitchen means interesting glimpses of the action there as well as interactions with the chefs. Under the direction of Alexander Hoppe, they cook up a creative, seasonally inspired six-course menu – delicate bites are served to whet the appetite; delicious petits fours round off the meal. Well-rounded flavours and a beautiful sense of balance are achieved, for example, in the excellent hamachi prepared in two ways: glazed slices and a tender, spicy tartare, accompanied by fine strips of kohlrabi, yuzu gel as a successful contrast, and subtly sour buttermilk and aromatic oil from daikon sprouts as a sauce. Equally fantastic is the rack of lamb from Quercy with artichoke and vadouvan jus. Very well chosen wine pairings accompany the menu. The waitstaff are friendly and knowledgeable – the kitchen team partakes in serving the food and the chef is on hand to explain the dishes.'),

('FZN by Björn Frantzén', 'Atlantis The Palm Jumeirah, Crescent Road, Dubai', 'Dubai', 'Dubai', '$$$$', 'Modern Cuisine', 55.1182319, 25.1320377, '+971501076322', 'https://guide.michelin.com/en/dubai-emirate/dubai/restaurant/fzn-by-bjorn-frantzen', 'https://www.restaurantfzn.com/', '3 Stars', 3, 0, 'Air conditioning,Car park,Counter dining,Interesting wine list,Valet parking,Wheelchair access', 'With a simple ring of a doorbell, you are transported to an elevated dining experience set in what looks like someone''s home. It starts in the Scandi-inspired sitting room for canapes and aperitifs; then, dinner takes place around an impressive open kitchen, where you are greeted by the chefs before service begins. An array of dishes showcases the blend of Asian and Scandinavian influences that make great use of the finest luxury ingredients, such as shellfish from the Norwegian Sea and turbot from Brittany. The team''s craft and precision present a superb balance of flavour and texture seen across all the plates.');

INSERT INTO accommodations (name, city, category, address, photo_url) VALUES
('Hotel Le Bristol', 'Paris', 'Hôtel 5 étoiles', '112 Rue du Faubourg Saint-Honoré, Paris', 'https://images.unsplash.com/photo-1566073771259-6a8506099945'),
('Villa Copenhagen', 'Copenhagen', 'Boutique Hôtel', 'Tietgensgade 35-39, Copenhagen', 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa'),
('Hotel Adlon Kempinski', 'Berlin', 'Hôtel de luxe', 'Unter den Linden 77, Berlin', 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb'),
('The Savoy', 'London', 'Hôtel historique', 'Strand, London', 'https://images.unsplash.com/photo-1564501049412-61c2a3083791'),
('Grand Hotel Stockholm', 'Stockholm', 'Hôtel 5 étoiles', 'Södra Blasieholmshamnen 8, Stockholm', 'https://images.unsplash.com/photo-1571896349842-33c89424de2d'),
('Hotel Alfonso XIII', 'Seville', 'Palace Hôtel', 'San Fernando 2, Seville', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'),
('Mandarin Oriental', 'Barcelona', 'Hôtel urbain', 'Passeig de Gràcia 38-40, Barcelona', 'https://images.unsplash.com/photo-1590490360182-c33d57733427'),
('Badrutt''s Palace Hotel', 'St. Moritz', 'Resort', 'Via Serlas 27, St. Moritz', 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c'),
('Aman Venice', 'Venice', 'Hôtel de charme', 'Palazzo Papadopoli, Venice', 'https://images.unsplash.com/photo-1455587734955-081b22074882'),
('Four Seasons Firenze', 'Florence', 'Hôtel jardin', 'Borgo Pinti 99, Florence', 'https://images.unsplash.com/photo-1468824357306-a439d58ccb1c'),
('Hotel de France', 'Paris', 'Hôtel historique', '108 Rue de Richelieu, Paris', 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a');
